name: KDebugger Ready

on:
  push:
    branches:
      - master

jobs:
  update_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete Existing Branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git push origin --delete kdbg || echo "Branch 'kdbg' does not exist"

      - name: Create Branch
        run: |
          git checkout -b kdbg

      - name: Update Namespaces
        run: |
          find . -type f -name '*.cs' -exec sed -i 's/ShizoGames\\([.;]\\| \\)/KDebugger.Plugins.ShizoGames/g' {} +

      - name: Replace Editor Asmdef
        run: |
          find . -type f -name 'ShizoGames.*.Editor.asmdef' -execdir bash -c 'echo -e "{\r\n    \"reference\": \"KDebugger.Plugins.Editor\"\r\n}" > "{}" && mv "{}" "KDebugger.Plugins.Editor.Reference.asmref"' \;

      - name: Replace Runtime Asmdef
        run: |
          find . -type f -name 'ShizoGames.*.asmdef' -execdir bash -c 'echo -e "{\r\n    \"reference\": \"KDebugger.Plugins\"\r\n}" > "{}" && mv "{}" "KDebugger.Plugins.Reference.asmref"' \;

      - name: Remove .asmdef.meta Files
        run: |
          find . -type f -name 'ShizoGames.*.asmdef.meta' -exec rm {} +

      - name: Push Branch
        run: |
          git add .
          git commit -m "KDebugger Ready"
          git push origin kdbg
