name: KDebugger Ready

on:
  push:
    branches:
      - master

jobs:
  update_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout Branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout kdbg || git checkout -b kdbg

      - name: Rebase from master
        run: |
          git fetch origin master
          git rebase origin/master

      - name: Update Namespaces
        run: |
          find . -type f -name '*.cs' -exec sed -i -r 's/ShizoGames([.;]|\s*\{)/KDebugger.Plugins.ShizoGames\1/g' {} +

      - name: Replace Editor Asmdef
        run: |
          find . -type f -name 'ShizoGames.*.Editor.asmdef' -execdir bash -c 'echo -e "{\r\n    \"reference\": \"KDebugger.Plugins.Editor\"\r\n}" > "{}" && mv "{}" "KDebugger.Plugins.Editor.Reference.asmref"' \;
          find . -type f -name 'ShizoGames.*.Editor.asmdef.meta' -execdir bash -c 'sed -i "s/^guid: .*$/guid: $(uuidgen)/g" > "{}" && mv "{}" "KDebugger.Plugins.Editor.Reference.asmref.meta"' \;

      - name: Replace Runtime Asmdef
        run: |
          find . -type f -name 'ShizoGames.*.asmdef' -not \( -name '*.Editor.asmdef' \) -execdir bash -c 'echo -e "{\r\n    \"reference\": \"KDebugger.Plugins\"\r\n}" > "{}" && mv "{}" "KDebugger.Plugins.Reference.asmref"' \;
          find . -type f -name 'ShizoGames.*.asmdef.meta' -not \( -name '*.Editor.asmdef.meta' \) -execdir bash -c 'sed -i "s/^guid: .*$/guid: $(uuidgen)/g" > "{}" && mv "{}" "KDebugger.Plugins.Reference.asmref.meta"' \;

      - name: Remove .asmdef.meta Files
        run: |
          find . -type f -name 'ShizoGames.*.asmdef.meta' -exec rm {} +

      - name: Commit Branch
        run: |
          git add .
          git commit -m "KDebugger Ready"
          git pull --rebase origin kdbg

      - name: Push Branch
        run: |
          git push --force origin kdbg
